import { Component, useEffect, useMemo, useRef, useState, type ErrorInfo, type ReactNode } from 'react'
import { ArrowUpRight, Home as HomeIcon, Info, Instagram, MapPin, Menu as MenuIcon, Phone, Search, X } from 'lucide-react'
import { menuCategories } from '@/data/menuData'

const instagramUrl = 'https://www.instagram.com/pablo.cafe2020/'
const photos = {
  hero: 'https://images.pexels.com/photos/11287941/pexels-photo-11287941.jpeg?auto=compress&cs=tinysrgb&w=1600',
  river: 'https://images.pexels.com/photos/36224723/pexels-photo-36224723.jpeg?auto=compress&cs=tinysrgb&w=1200',
  coffee: 'https://images.pexels.com/photos/6612662/pexels-photo-6612662.jpeg?auto=compress&cs=tinysrgb&w=1000',
  matcha: 'https://images.pexels.com/photos/30494513/pexels-photo-30494513.jpeg?auto=compress&cs=tinysrgb&w=1200',
  dessert: 'https://images.pexels.com/photos/33384164/pexels-photo-33384164.jpeg?auto=compress&cs=tinysrgb&w=1000',
  interior: 'https://images.pexels.com/photos/18617712/pexels-photo-18617712.jpeg?auto=compress&cs=tinysrgb&w=1400',
}

type Locale = 'en' | 'ar'
const DEFAULT_LOCALE: Locale = 'en'
const isLocale = (value: string | null): value is Locale => value === 'en' || value === 'ar'
const getStoredLocale = (): Locale => {
  try {
    const value = sessionStorage.getItem('pablo-locale')
    return isLocale(value) ? value : DEFAULT_LOCALE
  } catch {
    return DEFAULT_LOCALE
  }
}
const getCopy = (locale: string | null | undefined) => {
  const safeLocale: Locale = isLocale(locale ?? null) ? locale as Locale : DEFAULT_LOCALE
  return copy[safeLocale]
}
const readSession = (key: string) => { try { return sessionStorage.getItem(key) } catch { return null } }
const writeSession = (key: string, value: string) => { try { sessionStorage.setItem(key, value) } catch { /* Storage can be unavailable in privacy modes. */ } }
const copy = {
  en: { home: 'Home', menu: 'Menu', about: 'About', location: 'Find us', visit: 'Visit Pablo', menuTitle: 'Good things to come back to.', menuIntro: 'Coffee, colour, and something sweet beside the Nile.', explore: 'Explore the menu', directions: 'Get directions', call: 'Call Pablo', language: 'العربية', hero: 'A good cup finds you.', sub: 'A riverside café for slow mornings, long conversations, and the little rituals that make a day feel better.', story: 'Not just a café. A state of mind.', follow: 'Follow along', address: 'Last Nile Corniche, next to Tarh El Bahr Café' },
  ar: { home: 'الرئيسية', menu: 'القائمة', about: 'عن بابلو', location: 'موقعنا', visit: 'زوروا بابلو', menuTitle: 'أشياء جميلة تعود إليها.', menuIntro: 'قهوة، ألوان، وحلوى بجوار النيل.', explore: 'استكشف القائمة', directions: 'الاتجاهات', call: 'اتصل ببابلو', language: 'English', hero: 'كوب جيد سيجدك.', sub: 'كافيه على النيل للصباح الهادئ، والحوارات الطويلة، والطقوس الصغيرة التي تجعل يومك أجمل.', story: 'ليست مجرد كافيه. إنها حالة مزاجية.', follow: 'تابعنا', address: 'آخر كورنيش النيل بجوار كافيه طرح البحر' },
}

function Button({ children, href, variant = 'primary' }: { children: ReactNode; href: string; variant?: 'primary' | 'secondary' | 'quiet' }) { return <a className={`button button-${variant}`} href={href}>{children}</a> }
function Reveal({ children, className = '' }: { children: ReactNode; className?: string }) { return <div className={`reveal ${className}`}>{children}</div> }
function Logo() { return <a className="logo" href="/" aria-label="Pablo Cafe"><img src="/assets/logo/image.png" alt="Pablo Cafe" /></a> }

function Nav({ path, locale, setLocale }: { path: string; locale: Locale; setLocale: (l: Locale) => void }) {
  const t = getCopy(locale); const [open, setOpen] = useState(false)
  const links = [[t.home, '/'], [t.menu, '/menu'], [t.about, '/about'], [t.location, '/location']]
  return <header className="site-header"><nav className="shell nav"><Logo /><div className="desktop-links">{links.map(([label, href]) => <a className={path === href ? 'active' : ''} href={href} key={href}>{label}</a>)}</div><div className="nav-actions"><button className="locale-toggle" onClick={() => setLocale(locale === 'en' ? 'ar' : 'en')} aria-label={t.language}>{t.language}</button><a className="nav-visit" href="/location">{t.visit}<ArrowUpRight size={15} /></a><button className="menu-toggle" onClick={() => setOpen(!open)} aria-expanded={open} aria-label={open ? 'Close navigation' : 'Open navigation'}>{open ? <X /> : <MenuIcon />}</button></div></nav>{open && <div className="mobile-panel"><div className="shell">{links.map(([label, href]) => <a href={href} key={href} onClick={() => setOpen(false)}>{label}<ArrowUpRight size={16} /></a>)}<a href={instagramUrl} target="_blank" rel="noreferrer">Instagram<ArrowUpRight size={16} /></a></div></div>}</header>
}

function Footer({ locale }: { locale: Locale }) { const t = getCopy(locale); return <footer className="footer"><div className="shell footer-grid"><div><Logo /><p>{t.sub}</p></div><div><span className="footer-label">Explore</span><a href="/menu">{t.menu}</a><a href="/about">{t.about}</a><a href="/location">{t.location}</a></div><div><span className="footer-label">Say hello</span><a href="tel:01142966997">011 429 66997</a><a href={instagramUrl} target="_blank" rel="noreferrer">@pablo.cafe2020</a></div></div><div className="shell footer-bottom"><span>© 2026 Pablo Cafe</span><span>{t.address}</span></div></footer> }

function PageIntro({ eyebrow, title, text }: { eyebrow: string; title: ReactNode; text?: string }) { return <section className="shell page-intro"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{text && <p className="intro-copy">{text}</p>}</section> }
function Home({ locale }: { locale: Locale }) { const t = getCopy(locale); return <><main><section className="hero"><img src={photos.hero} alt="Coffee and light in Pablo Cafe" /><div className="hero-shade" /><div className="shell hero-content"><p className="eyebrow">Pablo Cafe / by the Nile</p><h1>{t.hero}</h1><p>{t.sub}</p><div className="hero-actions"><Button href="/menu">{t.explore}</Button><Button href="/location" variant="secondary">{t.visit}</Button></div></div><span className="hero-stamp">GOOD<br />MOOD</span></section><Reveal><section className="shell story"><div className="story-copy"><p className="eyebrow">The Pablo feeling</p><h2>{t.story}</h2><p>{t.sub} Pablo is made for the in-between moments — the ones that deserve more time, better company, and something lovely to drink.</p><a className="text-link" href="/about">{t.about}<ArrowUpRight size={16} /></a></div><img src={photos.interior} alt="Warm Pablo Cafe interior" loading="lazy" /></section></Reveal><section className="counter"><div className="shell"><div className="section-head"><div><p className="eyebrow">From the counter</p><h2>Sip the <em>colour.</em></h2></div><a className="text-link" href="/menu">{t.menu}<ArrowUpRight size={16} /></a></div><div className="counter-grid"><figure><img src={photos.matcha} alt="Iced matcha drink" loading="lazy" /><figcaption>01 / daily drink</figcaption></figure><figure className="offset"><img src={photos.dessert} alt="Dessert at Pablo Cafe" loading="lazy" /><figcaption>02 / good dessert</figcaption></figure></div></div></section><div className="marquee" aria-label="Pablo Cafe tagline"><div>GOOD COFFEE <span>—</span> GOOD MOOD <span>—</span> STAY A LITTLE LONGER <span>—</span> GOOD COFFEE <span>—</span> GOOD MOOD <span>—</span></div></div><section className="shell location-tease"><img src={photos.river} alt="The Nile beside Pablo Cafe" loading="lazy" /><div><p className="eyebrow">Come find us</p><h2>By the Nile,<br /><em>in your element.</em></h2><p>{t.address}</p><Button href="/location" variant="secondary">{t.directions}</Button></div></section><section className="follow"><div className="shell"><Instagram size={26} /><p className="eyebrow">{t.follow}</p><h2>@pablo.<em>cafe2020</em></h2><Button href={instagramUrl} variant="secondary">Instagram</Button></div></section></main><Footer locale={locale} /></> }

function MenuPage({ locale }: { locale: Locale }) { const t = getCopy(locale); const [active, setActive] = useState('coffee'); const [query, setQuery] = useState(''); const category = menuCategories.find(c => c.id === active) ?? menuCategories[0]; const items = useMemo(() => category.items.filter(i => `${i.name} ${i.description}`.toLowerCase().includes(query.toLowerCase())), [category, query]); return <><main><PageIntro eyebrow="The Pablo menu" title={<>{t.menuTitle.split(' ').slice(0, 2).join(' ')}<br /><em>{t.menuTitle.split(' ').slice(2).join(' ')}</em></>} text={t.menuIntro} /><section className="shell menu-shell"><div className="menu-tools"><div className="category-nav" role="tablist">{menuCategories.map(item => <button key={item.id} className={active === item.id ? 'active' : ''} onClick={() => setActive(item.id)} role="tab" aria-selected={active === item.id}>{item.label}</button>)}</div><label className="search"><Search size={17} /><span className="sr-only">Search menu</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search menu" /></label></div><div className="menu-heading"><div><p className="eyebrow">01 / 04</p><h2>{category.label}</h2></div><p>{category.note}</p></div><div className="menu-grid">{items.map(item => <article className="menu-card" key={item.name}><img src={item.image} alt={item.name} loading="lazy" /><div><h3>{item.name}</h3><p>{item.description}</p>{item.price && <strong>{item.price}</strong>}</div></article>)}</div><p className="menu-note">Menu items and prices are updated in café. Ask our team about today's specials.</p></section></main><Footer locale={locale} /></> }
function AboutPage({ locale }: { locale: Locale }) { const t = getCopy(locale); return <><main><PageIntro eyebrow="A little about Pablo" title={<>Made for the<br /><em>good moments.</em></>} /><section className="shell about-feature"><img src={photos.interior} alt="Pablo Cafe interior" /><div><p className="eyebrow">Our space</p><h2>A little pause from the rush.<br /><em>A lot of room for living.</em></h2><p>{t.sub} Set beside the Nile, Pablo brings together a familiar table, drinks made with care, and an atmosphere that lets the conversation run long.</p></div></section><section className="about-river"><div className="shell"><p>Take your time.</p><strong>Stay for the view.</strong></div></section></main><Footer locale={locale} /></> }
function LocationPage({ locale }: { locale: Locale }) { const t = getCopy(locale); return <><main><PageIntro eyebrow="Find Pablo" title={<>Meet us<br /><em>by the Nile.</em></>} text={t.sub} /><section className="shell location-layout"><img src={photos.river} alt="The Nile beside Pablo Cafe" /><div><p className="eyebrow">Address</p><h2>{t.address}</h2><p className="eyebrow">Call us</p><a className="big-phone" href="tel:01142966997">011 429 66997</a><div className="location-buttons"><Button href="https://www.google.com/maps/search/?api=1&query=آخر+كورنيش+النيل+بجوار+كافيه+طرح+البحر">{t.directions}</Button><Button href="tel:01142966997" variant="secondary">{t.call}</Button></div></div></section></main><Footer locale={locale} /></> }

class AppErrorBoundary extends Component<{ children: ReactNode }, { hasError: boolean }> {
  state = { hasError: false }
  static getDerivedStateFromError() { return { hasError: true } }
  componentDidCatch(error: Error, info: ErrorInfo) { console.error('[v0] Pablo Cafe render error', error, info) }
  render() {
    if (this.state.hasError) return <main className="error-screen"><img src="/assets/logo/image.png" alt="Pablo Cafe" /><p className="eyebrow">Something went wrong / حدث خطأ</p><h1>Let&apos;s try that again.</h1><p>We&apos;re having a small moment. جرّب إعادة تحميل الصفحة.</p><button className="button button-primary" onClick={() => window.location.reload()}>Reload / إعادة التحميل</button></main>
    return this.props.children
  }
}

function App() { const [path, setPath] = useState(window.location.pathname); const [locale, setLocale] = useState<Locale>(() => getStoredLocale()); const [splash, setSplash] = useState(() => !readSession('pablo-seen')); useEffect(() => { const click = (e: MouseEvent) => { const a = (e.target as HTMLElement).closest('a'); if (a && a.origin === location.origin && !a.hash) { e.preventDefault(); history.pushState({}, '', a.pathname); setPath(a.pathname); window.scrollTo({ top: 0, behavior: 'instant' as ScrollBehavior }) } }; const pop = () => setPath(location.pathname); document.addEventListener('click', click); addEventListener('popstate', pop); return () => { document.removeEventListener('click', click); removeEventListener('popstate', pop) } }, []); useEffect(() => { document.documentElement.lang = locale; document.documentElement.dir = locale === 'ar' ? 'rtl' : 'ltr'; writeSession('pablo-locale', locale); document.title = `Pablo Cafe — ${locale === 'ar' ? 'كوب جيد سيجدك' : 'A good cup finds you'}` }, [locale]); useEffect(() => { if (!splash) return; const timer = setTimeout(() => { writeSession('pablo-seen', '1'); setSplash(false) }, 2200); return () => clearTimeout(timer) }, [splash]); const page = path === '/menu' ? <MenuPage locale={locale} /> : path === '/about' ? <AboutPage locale={locale} /> : path === '/location' ? <LocationPage locale={locale} /> : <Home locale={locale} />; return <div className={locale === 'ar' ? 'rtl' : ''}>{splash && <div className="splash"><img src="/assets/logo/image.png" alt="Pablo Cafe" /><div className="loader-line"><span /></div><p>{locale === 'ar' ? 'خذ وقتك.' : 'Take your time.'}</p><button onClick={() => { writeSession('pablo-seen', '1'); setSplash(false) }}>Skip</button></div>}<Nav path={path} locale={locale} setLocale={setLocale} />{page}<nav className="bottom-nav" aria-label="Mobile navigation">{[[HomeIcon, getCopy(locale).home, '/'], [MenuIcon, getCopy(locale).menu, '/menu'], [MapPin, getCopy(locale).location, '/location'], [Info, getCopy(locale).about, '/about']].map(([Icon, label, href]) => <a className={path === href ? 'active' : ''} href={href as string} key={href as string}><Icon size={18} /><span>{label as string}</span></a>)}</nav></div> }
export default function SafeApp() { return <AppErrorBoundary><App /></AppErrorBoundary> }
export { photos }
export type { Locale }
